export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER';
export const SET_CURRENT_TEST   = 'SET_CURRENT_TEST';
export const SET_LEFT_SIDEBAR_TAB_ID = 'SET_LEFT_SIDEBAR_TAB_ID';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const UNSELECT_QUESTION = 'UNSELECT_QUESTION';
export const SAVE_TEST_QUESTIONS = 'SAVE_TEST_QUESTIONS';