export const TOGGLE_CREATE_TEST_MODAL = 'TOGGLE_CREATE_TEST_MODAL';
export const SHOW_CREATE_TEST_MODAL   = 'SHOW_CREATE_TEST_MODAL';
export const HIDE_CREATE_TEST_MODAL   = 'HIDE_CREATE_TEST_MODAL';
export const UPDATE_NEW_TEST          = 'UPDATE_NEW_TEST';
